#ifndef MENU_HEADER_H_INCLUDED
#define MENU_HEADER_H_INCLUDED

#define MENU_ID 1
#define PARAMETRIC_LINE_ID 2
#define DDA_LINE_ID 3
#define MIDPOINT_LINE_ID 4
#define DIRECT_ELLIPSE_ID 5
#define POLAR_ELLIPSE_ID 6
#define MIDPOINT_ELLIPSE_ID 7
#define POLYGON_CLIPPING_ID 8
#define BEZIER_CUBE_CURVE_ID 9
#define HERMITE_CUBE_CURVE_ID 10
#define SPLINES_GUIDED_ID 11
#define SPLINES_PASS_ID 12
#define CAMERA_COORDINATE_ID 13
#define SAVE_ID 14
#define LOAD_ID 15
#define EXIT_ID 16

#endif // MENU_HEADER_H_INCLUDED

